---
name: PR Preview

"on":
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: write
  pull-requests: write

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Prepare site
        if: github.event.action != 'closed'
        run: |
          mkdir _site
          rsync -av --exclude .git --exclude .github --exclude CNAME ./ _site/

      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./_site
          preview-branch: main
          pages-base-url: ${{ github.repository_owner }}.github.io
